name: UltimateFood
version: '1.5.0'
main: net.juligame.ultimatefoods.UltimateFoods
api-version: '1.21'
authors: [ JuliGame, RoloGod ]
description: The Ultimate Food plugin ;)
commands:
  ultimatefood:
    description: The Ultimate Food plugin ;)
    aliases:
      - ultimatefoods
  uf:
    description: The Ultimate Food plugin ;)